### ISSUE TITLE
multiple-choice - partially correct ui is not clear

### ISSUE THREAD

**Issue by edeustace** [pie-framework/pie-elements#4]
<img width="697" alt="screen shot 2018-03-22 at 10 25 11" src="https://user-images.githubusercontent.com/101623/37776335-6ae117e2-2dbb-11e8-888a-356a29110c45.png">

In the above the correct answer is Sweden AND Finland. In evaluate mode the ui shows that Sweden is correct and adds a correct answer toggle, but it's not that clear that this response is only partially correct.

> The legacy component has the same issue.

**Comment by evaneus** [comment]
Maybe this?....

<img width="727" alt="screenshot 2018-07-09 12 04 18" src="https://user-images.githubusercontent.com/799323/42462100-44356a0c-8370-11e8-8034-9d23ebfae636.png">

**Comment by alex-alberto** [comment]
@edeustace we would like to mark this as P1, because it feels broken to teachers since students are not able to know what they did wrong when answering an item with the scenario you included in this ticket. Would you be able to add "[P1]" at the beginning fo the title line? (I don't have the ability to edit). Thanks!

**Comment by PowerMyLearningConnect** [comment]
Hi @edeustace 
I think the solution proposed by @evaneus would work for us.
So - every answer selected by the student would be marked as right or wrong.
Any right answers not selected by the student would show up like Finland above.
And wrong answers not selected by the student would not have any indicator next to it.
